### PR TITLE
A simple bower.json file for bower integration

### PR DESCRIPTION
**Pull request by j-kan**
Nothing fancy, but it was sufficient for my purposes.

### CODE REVIEW

**Comment by annevk** [comment]
I'm afraid this kind of data becomes stale. Can't bower get the information from GitHub?

**Comment by j-kan** [comment]
Hmm... I'm not a bower guru, but I'm not aware of a bower mechanism to auto-generate the information in this file.

However, I believe the only fields bower really needs are "name", "version", and "main", so I could get rid of all the other fields.

**Comment by annevk** [comment]
https://github.com/annevk/webvtt/commit/3438c8385d06c57d88d91743e309e64e17b326fe

**Comment by annevk** [comment]
I guess we can go with this for now. Thanks.

**Pull request closed without merging**
