### PR TITLE
Incorporate tests from WPT and make parser more compliant

### LINKED ISSUE #8: Support `position:10%,start` cue setting
http://dev.w3.org/html5/webvtt/#dfn-webvtt-text-position-cue-setting

(Also see https://www.w3.org/Bugs/Public/show_bug.cgi?id=28521 )

### LINKED ISSUE #17: Timestamps with one digit allowed
The [spec](https://www.w3.org/TR/webvtt1/#webvtt-timestamp) requires that a WebVTT timestamp has two or more ASCII digits for hours (if non-zero) and two ASCII digits for minutes.

```
WEBVTT

1:23.456 --> 1:23:45.678
```

However, the validator accepts above input as valid. The first value length in a timestamp before the first colon is not checked.

### PR DESCRIPTION
**Pull request by dontcallmedom**
fixes #8 
fixes #17
and a bunch of other fixes detailed in the commits.

The test suite still have failures due to lack of "REGION" support

all the files in test/wpt-file-parsing were generated from the WPT test suite, with a slightly modified build.py to also export js files separately
```diff
--- a/webvtt/parsing/file-parsing/tools/build.py
+++ b/webvtt/parsing/file-parsing/tools/build.py
@@ -88,6 +88,8 @@ def generate_test(test_path, output_dir):
     vtt_file_path = path.join(vtt_file_dir, vtt_file_name)
     vtt_file_rel_path = path.join('support', vtt_file_name)
 
+    js_file_path = path.join(vtt_file_dir, test_basefilename + '.js')
+
     # Write html file
     with open(html_file_path, 'w') as output:
         html = (TEMPLATE.replace('%test_name', test_name)
@@ -96,6 +98,8 @@ def generate_test(test_path, output_dir):
                         .replace('%vtt_file_rel_path', vtt_file_rel_path))
         output.write(html)
 
+    with open(js_file_path, 'w') as output:
+        output.write(test_js)

```

### CODE REVIEW

**Comment by annevk** [comment]
Wow, cool. I'm inclined to accept this as-is. Is it okay if I squash things? Also, I'm wondering if there's a better home for this project somewhere as I'm not interested in driving this much myself anymore.

**Comment by annevk** [comment]
Actually, rebase and merge might be good since the commits are all clean.

**Comment by dontcallmedom** [comment]
re new home, I could bring it over in @w3c (with a new repo name given that w3c/webvtt is where the spec is developed); I'm happy to maintain it for now given that it matches an itch I need to scratch

re merging approach, I've tried to keep the commits atomic and meaningful, but I'm happy for you to take the approach you prefer

**Comment by annevk** [comment]
Sounds reasonable. I can transfer it to you and then you can transfer it there.

**Comment by annevk** [comment]
It seems like you'll need to delete the fork first.

**Comment by dontcallmedom** [comment]
fork deleted

**Pull request merged**
